- gravitee-gateway-http-client/gravitee-gateway-http-client-core/pom.xml
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/SyncManagerTest.java
- pom.xml
Unable to manually deploy API via Events.
> Features/event : Manually deploy API to the Gateway

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
> Published events are always created into the sync manager

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/SyncManagerTest.java
This closes #36 and closes #46
> Gateway must undeploy API if its last event type is UNPUBLISH_API

- gravitee-gateway-http-client/gravitee-gateway-http-client-vertx/src/main/java/io/gravitee/gateway/http/vertx/VertxHttpClient.java
> feature(pipelining): Add pipelining for HTTP client

- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/AbstractHttpInvoker.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/QueryParametersTest.java
> fix(http): Encode HTTP query parameters when building the request URI

- CONTRIBUTING.adoc
Just a few typos noticed when reading the contributing doc
> fix small typos

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> fix(reporter): Update the configuration file for elasticsearch reporter

- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/AbstractHttpInvoker.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/loadbalancer/LoadBalancerSupportStrategy.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/loadbalancer/RandomLoadBalancerStrategy.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/loadbalancer/RoundRobinLoadBalancerStrategy.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/loadbalancer/WeightedLoadBalancerStrategy.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/loadbalancer/WeightedRandomLoadBalancerStrategy.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/loadbalancer/WeightedRoundRobinLoadBalancerStrategy.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/ApiLoaderInterceptor.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/ServiceUnavailableTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/junit/rules/ApiDeployer.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/junit/rules/ApiPublisher.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/junit/stmt/ApiDeployerStatement.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/junit/stmt/ApiPublisherStatement.java
Endpoint is no more reachable if healthcheck service marks it with DOWN state
Closes gravitee-io/issues#92
> feat(endpoint): Disable automatically unavailable endpoint

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/AbstractHttpInvoker.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/Policy.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/AbstractPolicyChain.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/PolicyImpl.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/RequestPolicyChain.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/ResponsePolicyChain.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/StreamablePolicyChain.java
- gravitee-gateway-policy/src/test/java/io/gravitee/policy/FailurePolicy.java
- gravitee-gateway-policy/src/test/java/io/gravitee/policy/StreamablePolicy.java
- gravitee-gateway-policy/src/test/java/io/gravitee/policy/SuccessPolicy.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/impl/DefaultReactor.java
> Request content streaming using @OnRequestContent

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/impl/DefaultReactor.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxEmbeddedContainer.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerFactory.java
- pom.xml
> Upgrade vert.x to 3.3.0

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/validator/HttpClientValidator.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/validator/HttpClientValidatorTest.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-vertx/src/main/java/io/gravitee/gateway/http/vertx/VertxHttpClient.java
> feat(http): Add a proxy options between gateway and backend

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> feat(config): allow envvar to configure gravitee.yml

- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/AbstractHttpInvoker.java
> feat(invoker): Put the resolved endpoint in execution context attributes

- gravitee-gateway-reporting/src/main/java/io/gravitee/gateway/report/impl/ReporterServiceImpl.java
- gravitee-gateway-reporting/src/main/java/io/gravitee/gateway/report/impl/lmax/LmaxReporterService.java
> fix(reporter): Shutdown LMAX reporter before reporter processors

- pom.xml
> feat(policy): Rule description: backward compatibility

- gravitee-gateway-repository/src/main/java/io/gravitee/gateway/repository/plugins/RepositoryPluginHandler.java
> fix(gateway): Load only repository plugins required by the configuration

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/ResponseTimeHandler.java
- pom.xml
This closes gravitee-io/issues#113
> feat(analytics): add proxy latency data

- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/PolicyResolverImpl.java
- pom.xml
> feat(policy): Enable / disable a policy rule

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/SyncManagerTest.java
> feat(repository): Preserve a single method to search for events.

- pom.xml
> chore: Upgrade definition module

- pom.xml
> chore: Upgrade vert.x and Netty.io dependencies

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/DefaultHttpInvoker.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/AbstractReactorHandler.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/el/EvaluableRequest.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/http/ContextualizedHttpServerRequest.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/ReactorTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
> feat(gateway): Add pathInfos (complete path without context-path)

- gravitee-gateway-services/gravitee-gateway-services-monitoring/src/main/java/io/gravitee/gateway/services/monitoring/event/Plugin.java
> fix(plugin): allow plugin with same id

- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/endpoint/impl/EndpointLifecycleManagerImpl.java
> fix(gateway): Use an iterator when removing item from the data structure

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- pom.xml
> feat(plan): Only plan with published status are deployed

- gravitee-gateway-http-client/gravitee-gateway-http-client-vertx/src/main/java/io/gravitee/gateway/http/vertx/VertxHttpClient.java
> feat(gateway): SSL is automatically enabled if endpoint schema is HTTPS

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/SyncManagerTest.java
This closes https://github.com/gravitee-io/issues/issues/319
> Add support for sharding tags exclusion

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> chore(gateway): Add missing ES cluster configuration property

- gravitee-gateway-http-client/gravitee-gateway-http-client-vertx/src/main/java/io/gravitee/gateway/http/vertx/VertxHttpClient.java
> fix(gateway): Set correct 'Host' header according to RFC2616

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/ResponseTimeHandler.java
> feat(gateway): Mesure the exact length of request and response content

- gravitee-gateway-services/gravitee-gateway-services-monitoring/src/main/java/io/gravitee/gateway/services/monitoring/MonitoringService.java
- gravitee-gateway-services/gravitee-gateway-services-monitoring/src/main/java/io/gravitee/gateway/services/monitoring/event/InstanceEventPayload.java
> Port instances display

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/builders/ProxyDefinitionBuilder.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/manager/ApiManagerTest.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/validator/ProxyValidatorTest.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/endpoint/impl/DefaultEndpointLifecycleManager.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/test/java/io/gravitee/gateway/http/core/endpoint/impl/DefaultEndpointLifecycleManagerTest.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/test/java/io/gravitee/gateway/http/core/endpoint/impl/tenant/MultiTenantAwareEndpointLifecycleManagerTest.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthCheck.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/test/java/io/gravitee/gateway/services/healthcheck/EndpointStatusManagerTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/DynamicRoutingGatewayTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/ServiceUnavailableTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/junit/stmt/ApiDeployerStatement.java
- pom.xml
> fix(endpoints): endpoints with same name are allowed

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/definition/Plan.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/plan/PlanPolicyChainResolver.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/security/PlanBasedSecurityProvider.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/security/PlanBasedSecurityProviderFilter.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/AbstractGatewayTest.java
> fix(gateway): Add plan information into the executioncontext

- pom.xml
> chore: Upgrade Vert.x to 3.4.1

- gravitee-gateway-resource/src/main/java/io/gravitee/gateway/resource/internal/ResourceManagerImpl.java
> fix(gateway): Check the correct assignable type

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- pom.xml
> feat(plugin): Allow to load plugins from multiple registries

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/DefaultHttpInvoker.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/logger/ProxyClientResponse.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/ResponseTimeHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- pom.xml
> feat(log): Request /response analysis

- pom.xml
> feat(dynamodb): update repository dependency

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> fix(gateway): Listen for all sharding tags

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/manager/ApiManagerTest.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
> fix(sync): Do not deploy API if there is no plan associated to it.

- pom.xml
> chore: Upgrade reporter API dependency

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthCheck.java
> fix(healthcheck): Set timeout on request

- gravitee-gateway-el/src/test/java/io/gravitee/gateway/el/EvaluableRequest.java
- gravitee-gateway-el/src/test/java/io/gravitee/gateway/el/SpelTemplateEngineTest.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/DefaultHttpInvoker.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/el/EvaluableRequest.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/http/ContextualizedHttpServerRequest.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/transaction/TransactionRequest.java
- gravitee-gateway-security/gravitee-gateway-security-apikey/src/main/java/io/gravitee/gateway/security/apikey/ApiKeySecurityProvider.java
- gravitee-gateway-security/gravitee-gateway-security-apikey/src/test/java/io/gravitee/gateway/security/apikey/ApiKeySecurityProviderTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/QueryParametersTest.java
- pom.xml
> fix(gateway): Update model to handle multiple values per query parameter

- gravitee-gateway-reporting/src/main/java/io/gravitee/gateway/report/impl/ReporterServiceImpl.java
- gravitee-gateway-services/gravitee-gateway-services-core/src/main/java/io/gravitee/gateway/services/impl/ServiceManagerImpl.java
> fix(gateway): Stop all services before the technical API

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/path/impl/AbstractPathResolver.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/test/ApiPathResolverTest.java
> Allows to select a policy path without taking care of case

- pom.xml
> fix(gateway): Make the policy fails in case of streaming issue

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> chore: Set default local configuration for ES connector over HTTP

- gravitee-gateway-services/gravitee-gateway-services-monitoring/pom.xml
- gravitee-gateway-services/gravitee-gateway-services-monitoring/src/main/java/io/gravitee/gateway/services/monitoring/MonitoringService.java
- gravitee-gateway-services/gravitee-gateway-services-monitoring/src/main/java/io/gravitee/gateway/services/monitoring/handler/MonitorHandler.java
> feat(monitoring): Add endpoint to technical API

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/pom.xml
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/validator/ProxyValidator.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
> chore: Remove unused dependencies

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/bin/gravitee
Fixes https://github.com/gravitee-io/issues/issues/944
> fix(cygwin-classpath): Added classpath conversion

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/DefaultInvoker.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/failover/FailoverInvoker.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/failover/FailoverRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
> fix(gateway): Better management of backpressure when failover is enabled

- pom.xml
> fix(failover): set the default timeout > 0

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiContextHandlerFactory.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiHandlerConfiguration.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/context/EvaluableExecutionContext.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/context/EvaluableRequest.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/context/ExecutionContextFactory.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/context/RequestExecutionContext.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/context/TemplateVariableProviderFactory.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/resources/META-INF/spring.factories
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/pom.xml
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/endpoint/impl/DefaultEndpointLifecycleManager.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/DefaultInvoker.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/failover/FailoverInvoker.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/resources/META-INF/spring.factories
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/test/java/io/gravitee/gateway/http/core/endpoint/impl/DefaultEndpointLifecycleManagerTest.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/test/java/io/gravitee/gateway/http/core/endpoint/impl/tenant/MultiTenantAwareEndpointLifecycleManagerTest.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/test/java/io/gravitee/gateway/http/core/invoker/DefaultInvokerTest.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-vertx/src/main/java/io/gravitee/gateway/http/vertx/VertxProxyConnection.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/AbstractReactorHandler.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/impl/DefaultReactorHandlerResolver.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/transaction/TransactionHandler.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/ReactorTest.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/transaction/TransactionHandlerTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerResponse.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/logback.xml
- pom.xml
Closes gravitee-io/issues#1048
> fix(gateway): Performance improvements

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/builder/RepositoryApiBuilder.java
Closes gravitee-io/issues#1050
> fix(sync): Do not deploy API changes after a single API deployment

- gravitee-gateway-services/gravitee-gateway-services-endpoint-discovery-consul/src/main/java/io/gravitee/gateway/services/endpoint/discovery/consul/verticle/EndpointDiscoveryConsulVerticle.java
Closes gravitee-io/issues#1087
> fix(consul): Do not update endpoint if target hasn't change

- pom.xml
Closes gravitee-io/issues#1092
> chore: Upgrade Vert.x to 3.1.5

- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/endpoint/EndpointLifecycleManagerFactory.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/endpoint/impl/tenant/MultiTenantAwareEndpointLifecycleManager.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/test/java/io/gravitee/gateway/http/core/endpoint/EndpointLifecycleManagerFactoryTest.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/test/java/io/gravitee/gateway/http/core/endpoint/impl/tenant/MultiTenantAwareEndpointLifecycleManagerTest.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckResolver.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/MultiTenantNotConfiguredGatewayTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/MultiTenantUnavailableGatewayTest.java
- pom.xml
Closes gravitee-io/issues#1056
> feat(tenant): An endpoint can be associated to multiple tenants

- gravitee-gateway-env/src/main/java/io/gravitee/gateway/env/EnvironmentBeanFactoryPostProcessor.java
> feat(configuration): allow _ for envvar

- pom.xml
Closes gravitee-io/issues#1137
> chore: Upgrade plugin-core dependency

- gravitee-gateway-env/src/main/java/io/gravitee/gateway/env/EnvironmentBeanFactoryPostProcessor.java
> fix(config): be able to set array in envvar

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
This closes gravitee-io/issues#1128
> fix: the first deployment fails sometime

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/impl/DefaultReactorHandlerRegistry.java
Closes gravitee-io/issues#1052
> feat(gateway): Blue green deployment

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/definition/Api.java
Closes gravitee-io/issues#1199
> fix(policy): Do not load a policy if the associated rule is not enabled

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/logging/LoggableClientRequest.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/DefaultInvoker.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/failover/FailoverRequest.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/logging/LoggableProxyConnection.java
- gravitee-gateway-http-client/gravitee-gateway-http-client-vertx/src/main/java/io/gravitee/gateway/http/vertx/VertxHttpClient.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/http/ContextualizedHttpServerRequest.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/transaction/TransactionRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/InvalidHttpMethodGatewayTest.java
- pom.xml
Closes gravitee-io/issues#1193
> fix(http): Add a specific enum value to handle unknown HTTP Method

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> feat(report): Index per type support

- gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/DefaultInvoker.java
Closes gravitee-io/issues#1250
> fix(gateway): Add the additional slash if asked by the consumer

- gravitee-gateway-standalone/gravitee-gateway-standalone-bootstrap/pom.xml
Closes gravitee-io/issues#1257
> chore: API Gateway Boostrapper is now executable

- gravitee-gateway-env/pom.xml
- gravitee-gateway-env/src/main/java/io/gravitee/gateway/env/EnvironmentBeanFactoryPostProcessor.java
- pom.xml
>  feat(config): support different type of configuration

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckResolver.java
> fix(healthcheck): check endpoints without tenants

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/http/HttpEndpointRuleHandler.java
- pom.xml
This closes gravitee-io/issues#1240
> feat: allows to display HC status transitions

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerResponse.java
Closes gravitee-io/issues#1352
> fix(gateway): Do not write or end the response if already closed

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/failover/FailoverRequest.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/context/EvaluableRequest.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/logging/LoggableClientRequest.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/http/ContextualizedHttpServerRequest.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/transaction/TransactionRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- pom.xml
Closes gravitee-io/issues#1355
> feat(gateway): Add the protocol scheme to the Request

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/definition/Api.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/metrics/PathMappingMetricsHandler.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/reporter/ReporterHandler.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/impl/DefaultReactor.java
- gravitee-gateway-services/gravitee-gateway-services-monitoring/src/main/java/io/gravitee/gateway/services/monitoring/MonitoringService.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxReactorHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/junit/stmt/ApiDeployerStatement.java
- pom.xml
This closes gravitee-io/issues#1312
> feat: display top paths/resources in analytics

- gravitee-gateway-services/gravitee-gateway-services-core/pom.xml
- gravitee-gateway-services/gravitee-gateway-services-core/src/main/java/io/gravitee/gateway/services/http/HttpServer.java
- gravitee-gateway-services/gravitee-gateway-services-core/src/main/java/io/gravitee/gateway/services/http/handler/metrics/micrometer/prometheus/PrometheusMetricsHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxFactory.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#1349
> feat(metrics): Add Prometheus support

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/SyncManagerTest.java
- pom.xml
This closes gravitee-io/issues#561
> feat: Allows to search and filter APIs

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/ScheduledSyncService.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/SyncManagerTest.java
Closes gravitee-io/issues#1367
> fix(gateway): Optimize sync API deployment process

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/client/vertx/VertxHttpClient.java
Closes gravitee-io/issues#1373
> feat(http): Add AES 256 cipher suite

- gravitee-gateway-core/pom.xml
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/factory/EndpointFactory.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/factory/spring/SpringFactoriesEndpointFactory.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/factory/template/EndpointContext.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/factory/template/TemplateAwareEndpointFactory.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/impl/EndpointGroupLifecycleManager.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/impl/EndpointGroupLifecycleManagerTest.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/impl/tenant/MultiTenantAwareEndpointLifecycleManagerTest.java
- gravitee-gateway-http/pom.xml
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxProxyConnection.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxProxyResponse.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/endpoint/HttpEndpointFactory.java
- gravitee-gateway-http/src/test/java/io/gravite/gateway/http/endpoint/HttpEndpointFactoryTest.java
Closes gravitee-io/issues#1401
> feat(endpoint): Variable resolution for endpoint's configuration

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/client/vertx/VertxHttpClient.java
Closes gravitee-io/issues#1456
> fix(http): Add more supported cipher suite for HTTP-client side

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/context/DefaultExecutionContext.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/context/EvaluableRequest.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/context/EvaluableResponse.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/context/ExecutionContextFactory.java
Closes gravitee-io/issues#1476
> feat(gateway): Inject the response into the expression language engine

- gravitee-gateway-security/gravitee-gateway-security-jwt/src/main/java/io/gravitee/gateway/security/jwt/policy/CheckSubscriptionPolicy.java
- gravitee-gateway-security/gravitee-gateway-security-oauth2/src/main/java/io/gravitee/gateway/security/oauth2/policy/CheckSubscriptionPolicy.java
- gravitee-gateway-services/gravitee-gateway-services-subscriptions-cache/src/main/java/io/gravitee/gateway/services/subscriptionscache/repository/SubscriptionRepositoryWrapper.java
- gravitee-gateway-services/gravitee-gateway-services-subscriptions-cache/src/main/java/io/gravitee/gateway/services/subscriptionscache/task/SubscriptionRefresher.java
Closes gravitee-io/issues#1474
> fix(plan): Choose the plan according to the subscription

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequestTest.java
Closes gravitee-io/issues#1468
> fix(gateway): Remove the port from the X-Forwarded-For header

- gravitee-gateway-dictionary/pom.xml
- gravitee-gateway-dictionary/src/main/java/io/gravitee/gateway/dictionary/DictionaryManager.java
- gravitee-gateway-dictionary/src/main/java/io/gravitee/gateway/dictionary/DictionaryTemplateProvider.java
- gravitee-gateway-dictionary/src/main/java/io/gravitee/gateway/dictionary/model/Dictionary.java
- gravitee-gateway-dictionary/src/main/java/io/gravitee/gateway/dictionary/spring/DictionaryConfiguration.java
- gravitee-gateway-dictionary/src/main/resources/META-INF/spring.factories
- gravitee-gateway-services/gravitee-gateway-services-sync/pom.xml
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/SyncManagerTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/spring/StandaloneConfiguration.java
- pom.xml
Closes gravitee-io/issues#1400
> feat(dictionary): Add global dictionary

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/impl/DefaultGroupLifecycleManager.java
- gravitee-gateway-services/gravitee-gateway-services-endpoint-discovery-consul/src/main/java/io/gravitee/gateway/services/endpoint/discovery/consul/verticle/EndpointDiscoveryConsulVerticle.java
> fix(api): allow apis with no endpoints groups

- README.adoc
> chore(README): update documentation

- README.adoc
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
Add dev profile in pom.xml and update README documentation
> feat(build): add dev profile and update documentation

- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/hearbeat/HeartbeatService.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> feat(monitoring): filter envvar

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- pom.xml
Closes gravitee-io/issues#1536
> feat(analytics): Add Host HTTP header into analytics

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/processor/StreamableProcessor.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/PolicyChain.java
Clsoes gravitee-io/issues#1563
> fix(gateway): Map exit handler in the streamable processor

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/impl/DefaultReactorHandlerRegistry.java
Closes gravitee-io/issues#1570
> fix(gateway): API handler should be removed after a redeployment

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/impl/DefaultGroupLifecycleManager.java
> fix(endpoints): skip stopping empty groups

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/ref/Reference.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/ref/impl/DefaultReferenceRegister.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolver.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/invoker/EndpointInvoker.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolverTest.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/dynamic-routing.json
Closes gravitee-io/issues#1515
> fix(endpoint): Do not resolve an endpoint with an unknown target

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiHandlerConfiguration.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/AbstractReactorHandler.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/context/DefaultExecutionContext.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/context/EvaluableExecutionContext.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/context/EvaluableRequest.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/context/EvaluableResponse.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/context/ExecutionContextFactory.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/context/TemplateVariableProviderFactory.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/context/provider/NodeProperties.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/context/provider/NodeTemplateVariableProvider.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/spring/ReactorConfiguration.java
- gravitee-gateway-reactor/src/main/resources/META-INF/spring.factories
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/ReactorTest.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/DummyReactorHandler.java
Closes gravitee-io/issues#1656
> feat(el): Add node information into the templating variables

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckResolver.java
> fix(hc): API HC should be available after disable HC at endpoint level

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-reactor/pom.xml
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/ReactorHandler.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/alert/AlertHandler.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/pom.xml
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckResolver.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckService.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/http/HttpEndpointRuleHandler.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/verticle/EndpointHealthcheckVerticle.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/node/GatewayNode.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/spring/StandaloneConfiguration.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- pom.xml
This closes gravitee-io/issues#63
> feat: allows to send an alert when the HC status changes

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckResolver.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/test/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckResolverTest.java
> fix(healthcheck): do no run heathcheck if endpoint HC is disabled

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/alert/AlertHandler.java
This closes gravitee-io/issues#1702
> fix: Response time is not correct

- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/PolicyFactoryImpl.java
Closes gravitee-io/issues#1715
> fix(policy): Inject configuration even when this latest is null

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
This closes gravitee-io/issues#1732
> fix: Response is handled twice

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerFactory.java
Closes gravitee-io/issues#1733
> fix(http): Handle 100 continue automatically

- pom.xml
> fix(authentication): secure all routes if needed

- gravitee-gateway-services/gravitee-gateway-services-apikeyscache/src/main/java/io/gravitee/gateway/services/apikeyscache/ApiKeyRefresher.java
- gravitee-gateway-services/gravitee-gateway-services-subscriptions-cache/src/main/java/io/gravitee/gateway/services/subscriptionscache/task/SubscriptionRefresher.java
- pom.xml
Closes gravitee-io/issues#1753
> feat(souscription): A subscription can be paused and resumed

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/endpoint/HttpEndpointFactory.java
Closes gravitee-io/issues#1740
> feat(gateway): Add default HTTP headers to endpoints

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/EndpointException.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/impl/EndpointGroupLifecycleManager.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/impl/EndpointGroupLifecycleManagerTest.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/http/HttpEndpointRuleHandler.java
Closes gravitee-io/issues#1838
> fix(endpoint): Endpoint configuration issue must be handle properly

- pom.xml
> chore(pom): update parent (vert.x)

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
> fix(plan) a depreciate plan cannot be redeployed

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/impl/DefaultGroupLifecycleManager.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/impl/EndpointGroupLifecycleManager.java
- gravitee-gateway-services/gravitee-gateway-services-endpoint-discovery/src/main/java/io/gravitee/gateway/services/endpoint/discovery/verticle/EndpointDiscoveryVerticle.java
This closes gravitee-io/issues#1865
> fix: Service discovery is not working anymore

- gravitee-gateway-el/src/main/java/io/gravitee/gateway/el/SpelTemplateEngine.java
- gravitee-gateway-el/src/test/java/io/gravitee/gateway/el/SpelTemplateEngineTest.java
- pom.xml
closes gravitee-io/issues#1820
> feat(el): add parse method to TemplateEngine to work with generic data type

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/security/PlanBasedAuthenticationHandler.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/security/PlanBasedAuthenticationHandlerEnhancer.java
- gravitee-gateway-security/gravitee-gateway-security-apikey/pom.xml
- gravitee-gateway-security/gravitee-gateway-security-apikey/src/main/java/io/gravitee/gateway/security/apikey/ApiKeyAuthenticationHandler.java
- gravitee-gateway-security/gravitee-gateway-security-apikey/src/test/java/io/gravitee/gateway/security/apikey/ApiKeyAuthenticationHandlerTest.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/AuthenticationContext.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/AuthenticationHandler.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/SecurityProviderManager.java
- gravitee-gateway-security/gravitee-gateway-security-jwt/src/main/java/io/gravitee/gateway/security/jwt/JWTAuthenticationHandler.java
- gravitee-gateway-security/gravitee-gateway-security-keyless/src/main/java/io/gravitee/gateway/security/keyless/KeylessAuthenticationHandler.java
- gravitee-gateway-security/gravitee-gateway-security-oauth2/src/main/java/io/gravitee/gateway/security/oauth2/OAuth2AuthenticationHandler.java
closes gravitee-io/issues#1884
> fix(plan): add criteria to select API-Key plan

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
Closes gravitee-io/issues#1922
> feat(gateway): Attach the sslsession to the request

- gravitee-gateway-security/gravitee-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/SecurityProviderManager.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/test/java/io/gravitee/gateway/security/core/SecurityProviderManagerTest.java
> fix(plan): The order of the security is not followed

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- pom.xml
This closes gravitee-io/issues#1951
> feat: Add an option to get hits by user agent in analytics dashboard

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/EndpointLifecycleManager.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/LoadBalancedEndpointGroup.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/impl/DefaultGroupLifecycleManager.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/impl/EndpointGroupLifecycleManager.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/ref/AbstractReference.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/ref/EndpointReference.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/ref/GroupReference.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/ref/Reference.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/ref/impl/DefaultReferenceRegister.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolver.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/failover/FailoverInvoker.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/failover/FailoverOptions.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/invoker/EndpointInvoker.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/invoker/InvokerFactory.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/loadbalancer/LoadBalancer.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/loadbalancer/LoadBalancerStrategy.java
Thanks to unicity of reference.
Closes gravitee-io/issues#1989
> feat(endpoint): Better management of endpoint management

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolver.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolverTest.java
Closes gravitee-io/issues#1939
> fix(endpoints): resolve endpoints with special characters in their name

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/reporter/ReporterHandler.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/pom.xml
Closes gravitee-io/issues#1993
> feat(log): Add API ID and timestamp to logs

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> fix(reporter): improve the default configuration

- gravitee-gateway-services/gravitee-gateway-services-endpoint-discovery/src/main/java/io/gravitee/gateway/services/endpoint/discovery/factory/impl/ServiceDiscoveryFactoryImpl.java
- gravitee-gateway-services/gravitee-gateway-services-endpoint-discovery/src/main/java/io/gravitee/gateway/services/endpoint/discovery/verticle/EndpointDiscoveryVerticle.java
Closes gravitee-io/issues#1311
> feat(eureka): Add support for Spring Core

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolver.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolverTest.java
> fix(endpoint): keep the last /

- gravitee-gateway-buffer/src/main/java/io/gravitee/gateway/buffer/netty/BufferImpl.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/invoker/EndpointInvoker.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LimitedLoggableClientRequest.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LimitedLoggableClientResponse.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LimitedLoggableProxyConnection.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientRequest.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientResponse.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableProxyConnection.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/processor/LoggableRequestProcessor.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/utils/LoggingUtils.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/logging/ApiLoggableRequestProcessor.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
closes gravitee-io/issues#1891
> feat(logging): add max size limit for log body message

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/plan/PlanPolicyChainResolver.java
This closes gravitee-io/issues#1948
> feat: Audit on API user from JWT

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerConfiguration.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerFactory.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#2037
> feat(http): Provide additional configurations for the HTTP server

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/processor/chain/AbstractStreamableProcessorChain.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/processor/provider/StreamableProcessorProviderChain.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/processor/provider/spring/SpringBasedProcessorSupplier.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/ResponseProcessorChainFactory.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/alert/AlertProcessor.java
Closes gravitee-io/issues#2039
> fix(gateway): Processor provider were executed before the previous one

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/impl/EndpointGroupLifecycleManager.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/verticle/EndpointHealthcheckVerticle.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/node/GatewayNode.java
This closes gravitee-io/issues#2054
> fix: Health-check is not well started with discovered endpoints

- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/hearbeat/HeartbeatService.java
This closes gravitee-io/issues#2067
> feat: Optimizing event recuperation

- pom.xml
Closes gravitee-io/issues#2057
> fix(metrics): Do not get metrics for particular client / path

- pom.xml
> feat(user): archive users

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolver.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolverTest.java
> fix(endpoint resolver): unable to select an endpoint

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
This closes gravitee-io/issues#2084
> feat: Allows to extend ES index mapping

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolver.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolverTest.java
This closes gravitee-io/issues#2155
> fix: Select a discovered endpoint

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- pom.xml
Closes gravitee-io/issues#2179
> feat(metrics): Improve metrics configuration

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientResponse.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/error/SimpleFailureProcessor.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ReactorVerticle.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerResponse.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxReactorTimeoutHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- pom.xml
Closes gravitee-io/issues#1834
> feat(http): Add server request timeout

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/node/GatewayNode.java
This closes gravitee-io/issues#2160
> fix: Alert engine service is not starting

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/verticle/EndpointHealthcheckVerticle.java
> fix(healthcheck): hc fails with empty groups

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableProxyConnection.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/proxy/ws/SwitchProtocolProxyResponse.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/ws/VertxWebSocketFrame.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/ws/VertxWebSocketProxyConnection.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerResponse.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxReactorHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxReactorTimeoutHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ws/VertxWebSocket.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ws/VertxWebSocketFrame.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ws/VertxWebSocketServerRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ws/VertxWebSocketServerResponse.java
- pom.xml
Closes gravitee-io/issues#1899
> feat(http): Add websocket support

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolver.java
> fix(endpoint): NPE if use dynamic routing and no endpoints are available

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
Closes gravitee-io/issues#1589
> fix(http): Handle client response exception (ex: connection was closed)

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/condition/evaluation/el/ExpressionLanguageBasedConditionEvaluator.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/logging/condition/evaluation/el/ExpressionLanguageBasedConditionEvaluatorTest.java
> fix(logging): do not fail if logging condition is in error

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/plan/PlanPolicyChainResolver.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/PolicyChain.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/SecurityPolicyChainResolver.java
- gravitee-gateway-security/gravitee-gateway-security-jwt/src/main/java/io/gravitee/gateway/security/jwt/policy/CheckSubscriptionPolicy.java
- gravitee-gateway-security/gravitee-gateway-security-jwt/src/test/java/io/gravitee/gateway/security/jwt/policy/CheckSubscriptionPolicyTest.java
- gravitee-gateway-security/gravitee-gateway-security-oauth2/src/main/java/io/gravitee/gateway/security/oauth2/policy/CheckSubscriptionPolicy.java
- gravitee-gateway-security/gravitee-gateway-security-oauth2/src/test/java/io/gravitee/gateway/security/oauth2/policy/CheckSubscriptionPolicyTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/policy/ValidateRequestPolicy.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/policy/ValidateResponsePolicy.java
closes gravitee-io/issues#2208
> Feat: Add response template keys

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/error/SimpleFailureProcessor.java
- pom.xml
This closes gravitee-io/issues#1997
> feat: Multi analytics dashboards

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/endpoint/HttpEndpointFactory.java
> fix(endpoint): do not deploy malformed endpoints

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- pom.xml
Closes gravitee-io/issues#2219
> feat(plan): Manage plan deployment using sharding tags

- pom.xml
> fix: Policy API is not up to date

- pom.xml
> fix(vertx): support vertx options as system property

- gravitee-gateway-security/gravitee-gateway-security-jwt/pom.xml
Closes gravitee-io/issues#2397
> fix(plan): Add missing bouncy castle dependency for nimbus

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxProxyConnection.java
Closes gravitee-io/issues#2431
> fix(gateway): Do not end http request if the request has been canceled

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/security/apikey/ApiKeyPlanBasedAuthenticationHandler.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/policy/security/ApiKeyPlanBasedAuthenticationHandlerTest.java
> fix(apikey): handle apikey plan if an apikey is provided

- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/DefaultPolicyManager.java
> fix(DefaultPolicyManager): NPE on create

- gravitee-gateway-security/gravitee-gateway-security-jwt/pom.xml
> chore(jwt): add nimbus libs

- pom.xml
> fix(spel): manage null result

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolver.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolverTest.java
- gravitee-gateway-services/gravitee-gateway-services-endpoint-discovery/src/main/java/io/gravitee/gateway/services/endpoint/discovery/verticle/EndpointDiscoveryVerticle.java
> fix(): service ID must not contains ':'

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientResponse.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxProxyResponse.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/TimeoutServerResponse.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerResponse.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/SimpleGatewayTest.java
- pom.xml
Closes gravitee-io/issues#2381
> fix(http): Keep the status message as part of the response for consumer

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolver.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolverTest.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/http/HttpEndpointRuleHandler.java
Closes gravitee-io/issues#2255
> fix(websocket): Add support for ws and wss protocols

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/plan/PlanPolicyChainResolver.java
- pom.xml
> feat: Add a sparkline graph on subscriptions list

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/path/impl/AbstractPathResolver.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/path/impl/ApiPathResolverImpl.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/RuleBasedPolicyResolver.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/test/ApiPathResolverTest.java
Closes gravitee-io/issues#2504
> fix(policy): Handle the case where no root path is defined for the API

- gravitee-gateway-security/gravitee-gateway-security-apikey/src/main/java/io/gravitee/gateway/security/apikey/ApiKeyAuthenticationHandler.java
- gravitee-gateway-security/gravitee-gateway-security-apikey/src/test/java/io/gravitee/gateway/security/apikey/ApiKeyAuthenticationHandlerTest.java
- pom.xml
> fix: API key is not logged in analytics anymore

- gravitee-gateway-security/gravitee-gateway-security-jwt/src/main/java/io/gravitee/gateway/security/jwt/policy/CheckSubscriptionPolicy.java
- gravitee-gateway-security/gravitee-gateway-security-oauth2/src/main/java/io/gravitee/gateway/security/oauth2/policy/CheckSubscriptionPolicy.java
> feat: Display client id and not token on logs for JWT/OAuth2 plans

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolver.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/invoker/EndpointInvoker.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableProxyConnection.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolverTest.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/invoker/EndpointInvokerTest.java
- gravitee-gateway-http/pom.xml
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
- gravitee-gateway-http/src/test/java/io/gravite/gateway/http/connector/VertxHttpClientTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ReactorVerticle.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxReactorHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/QueryParametersTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- pom.xml
> fix(requests): do not encode/decode query parameters by default

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
> fix(reporter): update api response time in case of error

- pom.xml
Closes gravitee-io/issues#2570
> Rx ratelimit

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/plan/PlanPolicyChainResolver.java
> feat(jwt): Set the end user from jwt token used in plan or api policies

- gravitee-gateway-repository/src/main/java/io/gravitee/gateway/repository/plugins/RepositoryPluginHandler.java
Closes gravitee-io/issues#2693
> fix(repository): Try to load the repository indefinitely

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/impl/DefaultReactor.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/NotFoundProcessorChainFactory.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/notfound/NotFoundProcessor.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/notfound/NotFoundReporter.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/spring/ReactorConfiguration.java
Separated processing of unhandled requests to handlers chain.
Getting request's body is quite tricky. Should it be reported though?
> Added reporting of unhandled HTTP-requests to API Gateway

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
Closes gravitee-io/issues#2811
> fix(gateway): Add SSL support for WSS

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/spring/StandaloneConfiguration.java
Closes gravitee-io/issues#2878
> feat(node): Use node factory instead of node implementation

- pom.xml
Closes gravitee-io/issues#2880
> chore: Upgrade dependencies for Gravitee.io plugins

- gravitee-gateway-security/gravitee-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/TokenExtractor.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/test/java/io/gravitee/gateway/security/core/TokenExtractorTest.java
- gravitee-gateway-security/gravitee-gateway-security-jwt/src/main/java/io/gravitee/gateway/security/jwt/JWTAuthenticationHandler.java
- gravitee-gateway-security/gravitee-gateway-security-jwt/src/test/java/io/gravitee/gateway/security/jwt/JWTAuthenticationHandlerTest.java
- gravitee-gateway-security/gravitee-gateway-security-oauth2/src/main/java/io/gravitee/gateway/security/oauth2/OAuth2AuthenticationHandler.java
- gravitee-gateway-security/gravitee-gateway-security-oauth2/src/test/java/io/gravitee/gateway/security/oauth2/OAuth2AuthenticationHandlerTest.java
> fix(plan): implements token extractor for plan selection

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/http/HttpEndpointRuleHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
- pom.xml
> feat(services): Add a user-agent header for all services requests

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/OnErrorProcessorChainFactory.java
Closes gravitee-io/issues#2928
> fix(path-mapping): Execute path-mapping processor also on response error

- pom.xml
Closes gravitee-io/issues#2963
> chore: Update node dependency

- pom.xml
> fix(prometheus): register HC service only on Prometheus

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/forward/XForwardForProcessor.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/processor/forward/XForwardForProcessorTest.java
Closes gravitee-io/issues#2937
> fix(forward): Remove the port from the x-forwarded-for header

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientResponse.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableProxyConnection.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
- pom.xml
> fix(log): do not log eventstream

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerConfiguration.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerFactory.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#2978
> feat(http): Add support for PKCS12 and PEM for HTTP server

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/bin/gravitee.bat
> fix(gravitee.bat): wrong comment syntax

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LimitedLoggableClientRequest.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LimitedLoggableClientResponse.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LimitedLoggableProxyConnection.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientResponse.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/utils/LoggingUtils.java
Closes gravitee-io/issues#3005
> fix: The max size configuration of reporters is not well handled

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/invoker/EndpointInvoker.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LimitedLoggableClientResponse.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LimitedLoggableProxyConnection.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientResponse.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableProxyConnection.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/processor/LoggableRequestProcessor.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/utils/LoggingUtils.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/logging/utils/LoggingUtilsTest.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/RequestProcessorChainFactory.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/logging/ApiLoggableRequestProcessor.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#3007
> feat: We should avoid to log binary content

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LimitedLoggableClientRequest.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientRequest.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientResponse.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableProxyConnection.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/processor/LoggableRequestProcessor.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/utils/LoggingUtils.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/logging/utils/LoggingUtilsTest.java
Closes gravitee-io/issues#2976
> fix: do not log stream event requests

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
Closes gravitee-io/issues#3056
> fix(http): Do not enable logActivity for HTTP client

- gravitee-gateway-repository/src/main/java/io/gravitee/gateway/repository/healthcheck/RateLimitRepositoryProbe.java
- pom.xml
Closes gravitee-io/issues#3091
> fix(health-check): Check rate-limiting repository asynchronously

- gravitee-gateway-services/gravitee-gateway-services-subscriptions-cache/src/main/java/io/gravitee/gateway/services/subscriptionscache/task/SubscriptionRefresher.java
> fix(subscriptions): add only accepted subscription to the cache

- pom.xml
Closes gravitee-io/issues#3191
> fix: Some calls are reported with a negative response time

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/alert/AlertProcessor.java
Closes gravitee-io/issues#3187
> feat(alert): Add support for geoip and user agent alerting processors

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerConfiguration.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerFactory.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#3160
> feat(http): Provide better of client authentication mode

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/notfound/NotFoundReporter.java
Closes gravitee-io/issues#3195
> fix: Log unknown path for unknown APIs

- pom.xml
Closes gravitee-io/issues#3298
> chore: Upgrade Policy API dependency

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxProxyConnection.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/PostContentGatewayTest.java
Closes gravitee-io/issues#3426
> fix(proxy): Send content-type even if no content to send

- gravitee-gateway-security/gravitee-gateway-security-jwt/pom.xml
- gravitee-gateway-security/gravitee-gateway-security-oauth2/pom.xml
- pom.xml
Closes gravitee-io/issues#3427
> Upgrade nimbus-jwt dependency

- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/hearbeat/HeartbeatService.java
Closes gravitee-io/issues#3206
> feat(multi-env): mix membership scopes MANAGEMENT & PORTAL

- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/DirectPolicyChain.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/SecurityPolicyChainResolver.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/test/java/io/gravitee/gateway/security/core/SecurityPolicyChainResolverTest.java
closes gravitee-io/issues#3513
> feat(policyChain): add PLAN_UNRESOLVABLE policy chain error key

- pom.xml
> fix(alert): move to api 1.3.0

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
- gravitee-gateway-http/src/test/java/io/gravite/gateway/http/connector/VertxHttpClientTest.java
- pom.xml
Closes gravitee-io/issues#2634
> feat(gateway): remove encodeURI

- pom.xml
Closes gravitee-io/issues#3535
> chore: Upgrade Jackson to fix CVE

- pom.xml
Closes gravitee-io/issues#3679
> chore: Upgrade Netty dependency

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/spring/StandaloneConfiguration.java
Closes gravitee-io/issues#3682
> fix(sync): API definition loading must be case-insensitive

- pom.xml
Closes gravitee-io/issues#3419
> chore: Upgrade gravitee-node dependency

- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/DirectPolicyChain.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/forward/XForwardForProcessor.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/processor/forward/XForwardForProcessorTest.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/SecurityPolicyChainProvider.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/test/java/io/gravitee/gateway/security/core/SecurityPolicyChainProviderTest.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/test/java/io/gravitee/gateway/security/core/SecurityPolicyResolverTest.java
Closes gravitee-io/issues#3689
> Merge 1.25.25

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/factory/template/TemplateAwareEndpointFactory.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/spring/StandaloneConfiguration.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- pom.xml
Closes gravitee-io/issues#3660
> feat(el): sandbox EL to whitelisted methods

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/context/ApiTemplateVariableProvider.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/definition/Api.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/DirectPolicyChain.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/Reactable.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/forward/XForwardForProcessor.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/DummyReactorHandler.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/ReactorHandlerRegistryTest.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/processor/forward/XForwardForProcessorTest.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/SecurityPolicyChainProvider.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/test/java/io/gravitee/gateway/security/core/SecurityPolicyChainProviderTest.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/test/java/io/gravitee/gateway/security/core/SecurityPolicyResolverTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/spring/StandaloneConfiguration.java
- pom.xml
Closes gravitee-io/issues#3792
> Merge 1.30.10

- pom.xml
Closes gravitee-io/issues#3754
> feat(alert): Add support for alert command

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> feat: Change the default values for the number of shards/replicas

- pom.xml
> fix(LinkedCaseInsensitiveMap): implement the missing methods

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/cors/CorsRequestProcessor.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/CorsRegexTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/CorsWildcardTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/cors_regex_origin.json
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/cors_wildcard_origin.json
- pom.xml
> fix(cors): add regex support

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/cors/CorsRequestProcessor.java
- gravitee-gateway-repository/src/main/java/io/gravitee/gateway/repository/healthcheck/RateLimitRepositoryProbe.java
- gravitee-gateway-services/gravitee-gateway-services-endpoint-discovery/src/main/java/io/gravitee/gateway/services/endpoint/discovery/verticle/EndpointDiscoveryVerticle.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/CorsRegexTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/CorsWildcardTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/cors_regex_origin.json
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/cors_wildcard_origin.json
- pom.xml
> chore: Merge 1.30.11

- pom.xml
Closes gravitee-io/issues#3888
> fix(reporter): Upgrade node-reporter dependency

- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/StreamablePolicyChain.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/StreamFailGatewayTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/policy/StreamFailer2Policy.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/policy/StreamFailerPolicy.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/stream-fail.json
Closes gravitee-io/issues#3599
> fix(policy): Cancel chain when a streaming issue occurs

- pom.xml
> fix(): rename view in category

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/RequestProcessorChainFactory.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/cors/CorsPreflightRequestProcessor.java
Closes gravitee-io/issues#3891
> feat(logging): CORS and unknown requests are supported and can be logged

- pom.xml
Closes gravitee-io/issues#3943
> chore: Upgrade alert-api dependency

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/http/HttpEndpointRuleHandler.java
> fix(HC):: handle response exception

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/transaction/TransactionProcessor.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/transaction/TransactionProcessorFactory.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/processor/transaction/TransactionProcessorTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ReactorVerticle.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxReactorHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxReactorTimeoutHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ws/VertxWebSocketReactorHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ws/VertxWebSocketServerRequest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- pom.xml
> feat: Allows to pass a request id in outgoing headers

- pom.xml
> feat(alert): Support for alert templates

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ws/VertxWebSocketServerRequest.java
- pom.xml
Closes gravitee-io/issues#4003
> fix(el): fix el initialization

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/plan/PlanPolicyChainProvider.java
Closes gravitee-io/issues#4044
> fix(plan): Set unknown application and plan on preflight-request

- gravitee-gateway-env/src/main/java/io/gravitee/gateway/env/GatewayConfiguration.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/impl/DefaultReactor.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/node/GatewayNode.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- pom.xml
> feat: Support zone in order to group analytics

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/ManagedEndpoint.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/factory/EndpointFactory.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/factory/spring/SpringFactoriesEndpointFactory.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/impl/EndpointGroupLifecycleManager.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/loadbalancer/LoadBalancer.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/loadbalancer/RandomLoadBalancer.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/loadbalancer/RoundRobinLoadBalancer.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/loadbalancer/WeightedLoadBalancer.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/loadbalancer/WeightedRandomLoadBalancer.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/loadbalancer/WeightedRoundRobinLoadBalancer.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/impl/EndpointGroupLifecycleManagerTest.java
- gravitee-gateway-core/src/test/java/io/gravitee/gateway/core/endpoint/impl/tenant/MultiTenantAwareEndpointLifecycleManagerTest.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/endpoint/AbstractEndpointFactory.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/endpoint/GrpcEndpointFactory.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/endpoint/HttpEndpointFactory.java
- gravitee-gateway-http/src/test/java/io/gravite/gateway/http/endpoint/ManagedEndpointFactoryTest.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointStatusDecorator.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/test/java/io/gravitee/gateway/services/healthcheck/http/ManagedEndpointRuleHandlerTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/http/RoundRobinLoadBalancingMultipleTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/http/echo.json
Closes gravitee-io/issues#3877
> feat(endpoint): Manage secondary endpoints

- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/PolicyMetadata.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/DefaultPolicyManager.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/PolicyContextFactory.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/PolicyMetadataBuilder.java
- gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/SpringPolicyContextProvider.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/policy/PolicyBuilder.java
- pom.xml
Closes gravitee-io/issues#3935
> feat(policy-context): add policy context capability

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Depends on gravitee-io/issues#3935
Closes gravitee-io/issues#3933
> feat(sandbox): sandbox Groovy shell

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerConfiguration.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerFactory.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#4060
> feat(websocket): Add support for StompJS

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/plan/PlanPolicyChainProvider.java
Closes gravitee-io/issues#4121
> fix(gateway): Fix merge

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/AbstractConnector.java
Closes gravitee-io/issues#4131
> fix(http): Disable log activity

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/RequestProcessorChainFactory.java
Closes gravitee-io/issues#4146
> fix(processor): Create a new processor for each incoming request

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/transaction/TraceparentHelper.java
> issue(gateway): #4152 disable sampled flag in traceparent

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/http/HttpEndpointRuleHandler.java
> fix: Add API information on HC logs

- gravitee-gateway-services/gravitee-gateway-services-endpoint-discovery/src/main/java/io/gravitee/gateway/services/endpoint/discovery/verticle/EndpointDiscoveryVerticle.java
> fix: Discovery is not working on a group which is not the first

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/plan/PlanPolicyChainProvider.java
> fix: bad merge of 1.30.14

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> fix(reporters): allow to configure property name of ILM

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/loadbalancer/WeightedRandomLoadBalancer.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/loadbalancer/WeightedRoundRobinLoadBalancer.java
…rocess
Closes gravitee-io/issues#4208
> fix(lb): Runtime ratio must be refreshed when an endpoint is out of p… 

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/RequestProcessorChainFactory.java
…r to use the trace value as the transaction id
Closes gravitee-io/issues#4212
> fix(transaction): Execute traceparent before the transaction processo… 

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/http/ws/WebSocketFrame.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/http/ws/WebSocketProxyConnection.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerConfiguration.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerFactory.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ws/VertxWebSocket.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ws/VertxWebSocketFrame.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- pom.xml
Closes gravitee-io/issues#4220
> fix(gateway): Add better support for websocket and continuation

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/cors/CorsPreflightRequestProcessor.java
> feat(CORS): attach message to request for CORS errors

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/pathmapping/PathMappingProcessor.java
> fix: Path mappings not correctly detected

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- pom.xml
Closes gravitee-io/issues#4256
> feat(proxy): allow use of system proxy in endpoint configuration

- pom.xml
Closes gravitee-io/issues#4227
> feat(apikey): allow apikey reactivation

- docker/Dockerfile
Linked to gravitee-io/issues#4375
> update AdoptOpenJDK image to 11.0.8

- gravitee-gateway-services/gravitee-gateway-services-heartbeat/pom.xml
- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/HeartbeatService.java
- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/HeartbeatThread.java
- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/event/InstanceEventPayload.java
- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/event/Plugin.java
- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/spring/HeartbeatConfiguration.java
- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/resources/plugin.properties
Fixes https://github.com/gravitee-io/issues/issues/4499
> Hearbeat -> Heartbeat renaming of package etc.

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/RequestProcessorChainFactory.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/forward/XForwardedPrefixProcessor.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/processor/forward/XForwardedPrefixProcessorTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
- pom.xml
Fixes https://github.com/gravitee-io/issues/issues/4434
> feat: forward x-forwarded-prefix to the backend endpoint

- pom.xml
Closes gravitee-io/issues#4557
> chore: upgrade gateway-api dependency

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerConfiguration.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerFactory.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#4065
> feat(http): Add support for TLS protocol options

- docker/Dockerfile
Addresses https://github.com/gravitee-io/issues/issues/4511
> Update AdoptOpenJDK Docker image to 11.0.9

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/AbstractConnector.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/AbstractHttpProxyConnection.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/grpc/GrpcConnector.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/http/HttpProxyConnection.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/http/ws/WebSocketProxyConnection.java
Closes gravitee-io/issues#4632
> fix(gateway): Graceful shutdown of http connections

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/error/templates/ResponseTemplateBasedFailureProcessor.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/processor/error/templates/ResponseTemplateBasedFailureProcessorTest.java
Closes gravitee-io/issues#4464
> feat(response-template): Define a default response template

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ws/VertxWebSocketReactorHandler.java
> fix(gateway): test existance of Upgrade into Connection header values

- gravitee-gateway-env/src/test/java/io/gravitee/gateway/env/GatewayConfigurationTest.java
Fixes https://github.com/gravitee-io/issues/issues/4476
> fix: unable to disable websocket support fix tests

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/definition/Api.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/flow/BestMatchPolicyResolver.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/flow/FlowProvider.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/flow/SimpleFlowProvider.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/RequestProcessorChainFactory.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/ResponseProcessorChainFactory.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/policy/plan/PlanProcessorProvider.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/flow/BestMatchFlowTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/flow/best-match-flow.json
- pom.xml
Closes gravitee-io/issues#4598
> feat(flow): Add best_match support

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerFactory.java
Closes gravitee-io/issues#4887
> fix(http): Disable HTTP by default

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
Closes gravitee-io/issues#4934
> refactor: log API deployment only if API is enabled

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/pathparameters/PathParametersIndexProcessor.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/processor/pathparameters/PathParametersIndexProcessorTest.java
> fix(processor): check if path parameter iterator has more elements

- pom.xml
Closes gravitee-io/issues#4769
> feat(assign-metrics): use custom metrics in reporter

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointRule.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/http/HttpEndpointRuleHandler.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/AbstractEndpointRule.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleCronHandler.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/verticle/EndpointHealthcheckVerticle.java
- pom.xml
> feat(management): be able to enable/disable health-check during some periods

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/definition/Api.java
> fix: reverse post step execution order

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/invoker/EndpointInvoker.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientRequest.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientResponse.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableProxyConnection.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/utils/LoggingUtils.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/logging/ApiLoggableRequestProcessor.java
> feat(management): improve API logging configuration

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleHandler.java
Closes gravitee-io/issues#5059
> fix(healthcheck): Return 502 in case connection error to the backend

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/definition/Api.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/flow/SimpleFlowProvider.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/flow/condition/CompositeConditionEvaluator.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/flow/policy/FlowResponsePolicyChain.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/PolicyChainFactory.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/flow/HeadPolicyOrderFlowTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/flow/StreamPolicyOrderFlowTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/flow/policy/Header1Policy.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/flow/policy/Header2Policy.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/flow/policy/Stream1Policy.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/flow/policy/Stream2Policy.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/flow/simple-request-flow.json
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/flow/simple-request-stream-flow.json
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/flow/simple-response-stream-flow.json
- pom.xml
Closes gravitee-io/issues#5054
> fix(flow): Use correct policy execution order

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientResponse.java
- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableProxyConnection.java
> fix(logging): write headers when initialize response proxy

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/verticle/EndpointHealthcheckVerticle.java
> fix(hc): handle DAYS time unit for the trigger

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/subscriptions/SubscriptionsCacheService.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/subscriptions/repository/SubscriptionRepositoryWrapper.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/subscriptions/task/SubscriptionRefresher.java
Closes gravitee-io/issues#5176
> fix(sync): Cache keys should use API Id

- pom.xml
Fixes https://github.com/gravitee-io/issues/issues/4715
> feat: allows to define a prefix for collections / tables

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerConfiguration.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerFactory.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#5194
> feat(http): Add SNI support to the gateway

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiContextHandlerFactory.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiHandlerConfiguration.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/FreePlanApiHandlerConfiguration.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/definition/Api.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/definition/DefinitionContext.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/plan/PlanPolicyResolver.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/security/FreePlanAuthenticationHandler.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/security/FreePlanAuthenticationHandlerEnhancer.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/security/PlanBasedAuthenticationHandlerEnhancer.java
- gravitee-gateway-security/gravitee-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/SecurityPolicyResolver.java
- gravitee-gateway-services/gravitee-gateway-services-localregistry/src/test/resources/registry/api-test2.json
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncService.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/apikeys/ApiKeysCacheService.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/subscriptions/SubscriptionsCacheService.java
- pom.xml
> feat(k8s): Define and process CRD to define API withour plan

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
- gravitee-gateway-services/gravitee-gateway-services-sync/pom.xml
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncService.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/healthcheck/ApiSyncProbe.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/spring/SyncConfiguration.java
- pom.xml
> feat: allow to detect when the gateway is up vs when it is ready

- pom.xml
> fix: change the repository version

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> feat: resource information in health API

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/hazelcast.xml
Closes gravitee-io/issues#5391
> fix(cluster): Disable auto detection for Hazelcast 4.x

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
- pom.xml
Closes gravitee-io/issues#4898
> feat(cache): Support the new caching abstraction layer

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncService.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/pom.xml
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#5104
> feat(cockpit): Propagate monitoring data to cockpit

- gravitee-gateway-reporting/pom.xml
- gravitee-gateway-reporting/src/main/java/io/gravitee/gateway/report/impl/NodeMonitoringReporterService.java
- gravitee-gateway-reporting/src/main/java/io/gravitee/gateway/report/spring/ReporterConfiguration.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/node/GatewayNode.java
Closes gravitee-io/issues#5432
> fix(node): Push node monitoring to the reporter service

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleHandler.java
> fix(management): catch all timeout exception and return an 504

- gravitee-gateway-security/gravitee-gateway-security-jwt/pom.xml
- pom.xml
Closes gravitee-io/issues#5471
> fix: APIM dependencies upgrade

- gravitee-gateway-env/src/main/java/io/gravitee/gateway/env/GatewayConfiguration.java
- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/HeartbeatService.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncService.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/SyncManagerTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Fixes https://github.com/gravitee-io/issues/issues/5357
> feat: allow to associate a gateway to environments

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- pom.xml
Closes gravitee-io/issues#5539
> fix(gateway): Do not try to resume an already ended request

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/bin/gravitee
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/bin/gravitee.bat
Closes gravitee-io/issues#5523
> chore: Downgrade heap size by default

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/definition/Api.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/path/impl/ApiPathResolverImpl.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/policy/plan/PlanPolicyResolver.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/error/templates/ResponseTemplateBasedFailureProcessor.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/manager/ApiManagerTest.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/processor/error/templates/ResponseTemplateBasedFailureProcessorTest.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/test/ApiPathResolverTest.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/test/java/io/gravitee/gateway/services/healthcheck/http/ManagedEndpointRuleHandlerTest.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/spring/StandaloneConfiguration.java
- pom.xml
* use last version of gravitee-definition
* replace Path with List<Rule>
* replace ResponseTemplates with Map<String, ResponseTemplate>
* adapting some unit tests
* call validation when registering an API
Closes gravitee-io/issues#4475
> feat(management): cleanup APIM swagger.json

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiHandlerConfiguration.java
Fixes https://github.com/gravitee-io/issues/issues/4460
> fix(management): platform policies fix policy manager bean naming

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/http/client-authentication-pem-support.json
Related to gravitee-io/issues#5642
> fix: reintroduce serializers and deserializers

- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/HeartbeatService.java
- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/HeartbeatThread.java
Closes gravitee-io/issues#5649
> fix(heartbeat): avoid queue being full by replacing it with topic

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/manager/ApiManagerTest.java
Closes gravitee-io/issues#5600
> fix: inconsistent Sharding Tags behavior compared to the documentation

- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/http/HttpConnector.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/http/ws/WebSocketUtils.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/ws/VertxWebSocketReactorHandler.java
> fix: handle Connection header with keep-alive in addition of Upgrade

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
- pom.xml
> feat(gateway): add api.deployedAt to context

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/node/GatewayNode.java
- pom.xml
Closes gravitee-io/issues#5668
> fix(monitor): report node monitor only and avoid npe

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/manager/ApiManagerTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
- pom.xml
Closes gravitee-io/issues#5726
> chore: bump jackson, json-smart, spring-integration versions

- pom.xml
Closes gravitee-io/issues#5764
> fix(probe): set probe status to "noReady" when starting

- pom.xml
Use spring 5.3.8
gravitee-io/issues#5606
> feat: bump gravitee-bom to 1.2

- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/HeartbeatService.java
> fix(gateway): link STARTED event with DEFAULT environment if no db

- pom.xml
> feat(resource-cache): update api-cache-provider version

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerConfiguration.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerFactory.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#4972
> feat(http): Add support for HAProxy ProxyProtocol

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
update gravitee.yml default configuration for mongo database
gravitee-io/issues#3661
> feat: upgrade mongo-driver

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleHandler.java
- pom.xml
> Fix failing health check

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> doc: fix 'timeout' typo

- gravitee-gateway-env/src/main/java/io/gravitee/gateway/env/GatewayConfiguration.java
- gravitee-gateway-services/gravitee-gateway-services-debug/src/main/java/io/gravitee/gateway/debug/sync/DebugSyncManager.java
- gravitee-gateway-services/gravitee-gateway-services-debug/src/test/java/io/gravitee/gateway/debug/sync/DebugSyncManagerTest.java
- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/HeartbeatService.java
- pom.xml
> feat: select gateway to execute debug request

- pom.xml
Closes gravitee-io/issues#6051
> fix(el): reintroduce request.method access

- pom.xml
Closes gravitee-io/issues#5996
> chore: Upgrade to gravitee-node to include missing dependencies

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncService.java
Closes gravitee-io/issues#5977
> fix(sync): Sync service is not reading the right configuration

- gravitee-gateway-services/gravitee-gateway-services-debug/src/main/java/io/gravitee/gateway/debug/vertx/VertxDebugService.java
> refactor: clean dead code for instances number in debug service

- gravitee-gateway-services/gravitee-gateway-services-debug/pom.xml
gravitee-io/issues#6068
**From 35.5 Mo to 85 Ko**
> chore: reduce zip size for debug service

- pom.xml
Closes gravitee-io/issues#5966
> fix(event): propagate node stop event when shutdown

- pom.xml
> feat: allow access to SSL attributes in EL TemplateEngine

- pom.xml
Closes gravitee-io/issues#5938
> fix(el): Add support for extra spaces before the statement

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml
- pom.xml
Closes gravitee-io/issues#6152
> chore: Update dependencies

- pom.xml
> feat: create generate http signature policy

- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/HeartbeatService.java
- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/HeartbeatThread.java
> fix(gateway): [gateway] heartbeat stops after 1h

- gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/HeartbeatService.java
- pom.xml
> fix: node stop event not well propagated

- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/http/UnexpectedErrorTest.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/policy/UnexpectedErrorPolicy.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/test/resources/io/gravitee/gateway/standalone/http/unexpected-error.json
Closes gravitee-io/issues#6489
> fix(sme): add cancel handler

- pom.xml
> chore: bump expression language version

- gravitee-gateway-security/gravitee-gateway-security-jwt/src/main/java/io/gravitee/gateway/security/jwt/policy/CheckSubscriptionPolicy.java
- gravitee-gateway-security/gravitee-gateway-security-jwt/src/test/java/io/gravitee/gateway/security/jwt/policy/CheckSubscriptionPolicyTest.java
> fix(plan): plan selection linked to the subscription

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/handler/SyncHandler.java
Closes gravitee-io/issues#6539
> fix(sync): Write HEAD before response's payload

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/impl/tenant/MultiTenantAwareEndpointLifecycleManager.java
- gravitee-gateway-dictionary/src/main/java/io/gravitee/gateway/dictionary/DictionaryTemplateProvider.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/Entrypoint.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/VirtualHost.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/impl/DefaultReactorHandlerRegistry.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/impl/HandlerEntryPointComparator.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/EntrypointResolverTest.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/ReactorHandlerRegistryTest.java
Closes gravitee-io/issues#6543
> fix: fix inconsistent entrypoint resolution

- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/handler/SyncHandler.java
Closes gravitee-io/issues#6541
> fix(sync): Send HEAD before response's payload

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/impl/DefaultReactorHandlerRegistry.java
Closes gravitee-io/issues#6553
> fix: avoid 404 and 500 error during api redeploy or stop

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/lifecycle/impl/tenant/MultiTenantAwareEndpointLifecycleManager.java
- gravitee-gateway-dictionary/src/main/java/io/gravitee/gateway/dictionary/DictionaryTemplateProvider.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/Entrypoint.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/VirtualHost.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/context/TemplateVariableProviderFactory.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/impl/DefaultReactorHandlerRegistry.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/impl/HandlerEntryPointComparator.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/EntrypointResolverTest.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/ReactorHandlerRegistryTest.java
- gravitee-gateway-security/gravitee-gateway-security-jwt/src/main/java/io/gravitee/gateway/security/jwt/policy/CheckSubscriptionPolicy.java
- gravitee-gateway-security/gravitee-gateway-security-jwt/src/test/java/io/gravitee/gateway/security/jwt/policy/CheckSubscriptionPolicyTest.java
- gravitee-gateway-services/gravitee-gateway-services-endpoint-discovery/src/main/java/io/gravitee/gateway/services/endpoint/discovery/EndpointDiscoveryService.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckService.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
- gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/handler/SyncHandler.java
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/pom.xml
- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/assembly/plugin-assembly.xml
- pom.xml
> Merge tag 3.12.2

- gravitee-gateway-services/gravitee-gateway-services-healthcheck/pom.xml
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckResolver.java
- gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/test/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckResolverTest.java
> fix(healthcheck): use GraviteeMapper instead of simple ObjectMapper

- gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/pom.xml
- pom.xml
> fix(reporter): resolve ES monitor reporters

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/impl/DefaultReactorHandlerRegistry.java
This reverts commit 038dc31694dfe46c2ce2a8db02cb6594eec1790d.
gravitee-io/issues#6601
> Revert "fix: avoid 404 and 500 error during api redeploy or stop"

- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/impl/DefaultReactorHandlerRegistry.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/EntrypointResolverTest.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/ReactorHandlerRegistryTest.java
Closes gravitee-io/issues#6543
> fix: fix entrypoints update

- .circleci/config.yml
- gravitee-gateway-handlers/gravitee-gateway-handlers-api/pom.xml
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/impl/DefaultReactorHandlerRegistry.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/EntrypointResolverTest.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/ReactorHandlerRegistryTest.java
https://github.com/gravitee-io/issues/issues/6140
> Merge 3.10.x into 3.12.x

- gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggableClientResponse.java
- pom.xml
> fix(logs): append headers/payload to client response

- gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/processor/pathparameters/PathParametersProcessorBenchmark.java
- gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/vertx/VertxHttpServerRequest.java
- gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/VirtualHost.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/EntrypointResolverTest.java
- gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/VirtualHostTest.java
Closes gravitee-io/issues#6574
> fix: properly handle vhost with http/2

- .circleci/config.yml
- pom.xml
Add a validation job in pr workflow that will run "mvn validate" command to check licenses and format (with prettier)
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-kxqjotqlca.chromatic.com)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/add-validate-job-in-pr-workflow/index.html)
_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.
> ci: add a validation job in pr workflow
