gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java, gravitee-gateway-services/gravitee-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/SyncManagerTest.java, gravitee-gateway-services/gravitee-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/builder/RepositoryApiBuilder.java
=> Start / stopping an API must not deploy the current definition

gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/invoker/AbstractHttpInvoker.java
don't compile a regex for each invoke
reuse the compiled pattern as it's thread safe
fix gravitee-io/issues/issues/129
=> AbstractHttpInvoker creates Regexp objects wastefully

gravitee-gateway-reporting/src/main/java/io/gravitee/gateway/report/impl/lmax/LmaxReporterService.java
it should at least warn about it to help diagnose the problem (slow
consumer, wrong disruptor sizing, etc..)
Note that if you currently have this problem on a high volume gateway
this commit will flood your logs : No pain, No gain
Please adjust the log level if you think warn is too hardcore
fix gravitee-io/issues/issues/134
=> Gravitee may silently drop some Reportable events

pom.xml
=> chore: Move to latest gateway-api dependency

gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/bin/gravitee, gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/bin/gravitee.bat
=> fix(gateway): Set default JVM options

gravitee-gateway-http-client/gravitee-gateway-http-client-vertx/src/main/java/io/gravitee/gateway/http/vertx/VertxHttpClient.java
=> fix(gateway): Remove port from Host header for default HTTP / HTTPS port

gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/SyncManager.java
=> fix(sync): Set log level to lower level when dealing with sharding tags

gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(healthcheck): Update default port from 8092 to 18082

gravitee-gateway-services/gravitee-gateway-services-core/src/main/java/io/gravitee/gateway/services/http/HttpServer.java, gravitee-gateway-services/gravitee-gateway-services-core/src/main/java/io/gravitee/gateway/services/http/configuration/HttpServerConfiguration.java, gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
fix(gateway): Allow disabling of authentication for internal node API based on config file
closes gravitee-io/issues#791
=> fix(gateway): Allow disabling of authentication for internal node API

gravitee-gateway-http-client/gravitee-gateway-http-client-core/src/main/java/io/gravitee/gateway/http/core/endpoint/impl/DefaultEndpointLifecycleManager.java
=>  fix(gateway): Avoid concurrentModificationException when stopping an API

gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
=> chore(yml): Remove usage of env variables from gravitee.yml

gravitee-gateway-handlers/gravitee-gateway-handlers-api/pom.xml, gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/endpoint/ApiManagementEndpoint.java, gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/endpoint/ApisManagementEndpoint.java, gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/endpoint/NodeApisEndpointInitializer.java, gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/spring/ApiHandlerConfiguration.java
This closes gravitee-io/issues#1601
=> fix: Technical API does not expose /_node/apis anymore

gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
Closes gravitee-io/issues#1634
=> fix(gateway): HTTP request must be resume if exit handler is called.

gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/endpoint/resolver/impl/TargetEndpointResolver.java
This closes gravitee-io/issues#1679
=> fix: Endpoints are not well selected when contains whitespace character

gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckResolver.java
=> fix(hc): do not select inherited cfg if no global config is present

gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
This closes gravitee-io/gravitee-alert-engine#22
=> fix: Unable to connect cluster remotely

gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerRequest.java, gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerResponse.java, gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxReactorHandler.java
Closes gravitee-io/issues#1913
=> fix(http2): Remove connection specific header fields for HTTP2 responses

gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckResolver.java
=> fix(hc): could not start an api with an empty endpoint group

gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
This closes gravitee-io/issues#1920
=> fix: configurable request timeout for analytics

gravitee-gateway-core/src/main/java/io/gravitee/gateway/core/processor/ProcessorFailure.java, gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/error/SimpleFailureProcessor.java, gravitee-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/processor/PolicyChainProcessorFailure.java
This closes gravitee-io/issues#2149
=> fix: Missing method when policy oauth2 fail

gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/endpoint/HttpEndpointFactory.java
This closes gravitee-io/issues#2303
=> fix: Reduce log level when trailing slash is missing in endpoint

gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
=> doc: describe how to forbid the use of api-key param/header

gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
=> fix: Port is missing in the configuration of rate limit

gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
Closes gravitee-io/issues#3189
=> fix: End user is not logged when a policy fail

gravitee-gateway-security/gravitee-gateway-security-apikey/src/main/java/io/gravitee/gateway/security/apikey/ApiKeyAuthenticationHandler.java
Closes gravitee-io/issues#3308
=> fix: Store metrics only if api key plan matches

gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/forward/XForwardForProcessor.java, gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/processor/forward/XForwardForProcessorTest.java
=> fix(processor): XForwardForProcessor should handle IPv6 value

pom.xml
spring 5.1.3 -> 5.2.5
snakeyaml 1.2.1 -> 1.2.6
json-path 2.2.0 -> 2.4.0
guava 26.0-jre -> 29.0-jre
jackson 2.9.8 -> 2.10.3
Closes gravitee-io/issues#3652
=> chore(dependencies): upgrade dependencies

gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/context/ApiTemplateVariableProvider.java, gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/definition/Api.java, gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/Reactable.java, gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/DummyReactorHandler.java, gravitee-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/ReactorHandlerRegistryTest.java
Closes gravitee-io/issues#3683
=> fix(api): Do not duplicate api's properties to avoid memory pressure

gravitee-gateway-services/gravitee-gateway-services-endpoint-discovery/src/main/java/io/gravitee/gateway/services/endpoint/discovery/verticle/EndpointDiscoveryVerticle.java
Closes gravitee-io/issues#3814
=> fix(service-discovery): Process ':' as a string and not an integer

gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
=> fix: Change the default values for the number of shards/replicas

gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#3354
=> feat(elasticsearch): Add default configuration for ES HTTP proxy

gravitee-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/transaction/TraceparentHelper.java
Depending to the long values generated by the UUID,
traceparent header may have invalid length
fix gravitee-io/issues#4122
=> issue(gateway): fix traceparent format issue

gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java
By using ConcurrentHashMap instead of HashMap.
close https://github.com/gravitee-io/issues/issues/4221
=> Fix ConcurrentModuficationException in VertxHttpClient.

gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerConfiguration.java, gravitee-gateway-standalone/gravitee-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxHttpServerFactory.java, gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Closes https://github.com/gravitee-io/issues/issues/4541
To get supported CipherSuites for current java-version do:
jrunscript -e "java.util.Arrays.asList(javax.net.ssl.SSLServerSocketFactory.getDefault().getSupportedCipherSuites()).stream().forEach(println)"
=> TLS Cipher Suite Configuration Option

gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Fixes https://github.com/gravitee-io/issues/issues/4744
=> feat: auto-enable geoip and user_agent when elasticsearch > 7.x

docker/Dockerfile
Updates to newer AdoptOpenJDK base image. Linked to https://github.com/gravitee-io/issues/issues/4964
=> Update AdoptOpenJDK image

gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleCronHandler.java
**Issue**
Fix https://github.com/gravitee-io/issues/issues/5041
Previously, the scheduled handler can never be cancelled as the wrong `timerId` was updated.
=> fix: update the correct timer id in CronHandler to be able to stop it

gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/hazelcast.xml
Closes gravitee-io/issues#5191
=> fix(heartbeat): Define max size on the heartbeat queue to avoid OOM

pom.xml
The 1.20 version contains a fix for timestamp logging to file by adding an accessor. This would be very nice to have rolled in.
=> Update reporter-api to version 1.20

gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleHandler.java
Take into account the first character of the 'path' field in healthcheck configuration. We add a '/' only if the 'path' does not start by '/' or '?'
Fixes gravitee-io/issues#5433
=> fix(healthcheck): query params without '/'

gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
Closes gravitee-io/issues#5517
=> fix(gateway): Consume the queue before releasing the request

gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleHandler.java
Closes gravitee-io/issues#5752
=> fix: API health check is duplicating slash in some case

gravitee-gateway-handlers/gravitee-gateway-handlers-api/pom.xml, gravitee-gateway-repository/pom.xml, gravitee-gateway-security/gravitee-gateway-security-apikey/pom.xml, gravitee-gateway-security/gravitee-gateway-security-jwt/pom.xml, gravitee-gateway-security/gravitee-gateway-security-oauth2/pom.xml, gravitee-gateway-services/gravitee-gateway-services-heartbeat/pom.xml, gravitee-gateway-services/gravitee-gateway-services-sync/pom.xml, gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml, pom.xml
=> Use repo dependencies from the new APIM monorepo

gravitee-gateway-handlers/gravitee-gateway-handlers-api/pom.xml, gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/manager/ApiManagerTest.java, gravitee-gateway-repository/pom.xml, gravitee-gateway-security/gravitee-gateway-security-apikey/pom.xml, gravitee-gateway-security/gravitee-gateway-security-jwt/pom.xml, gravitee-gateway-security/gravitee-gateway-security-oauth2/pom.xml, gravitee-gateway-services/gravitee-gateway-services-heartbeat/pom.xml, gravitee-gateway-services/gravitee-gateway-services-sync/pom.xml, gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml, pom.xml
=> Use repo dependencies from the new APIM monorepo - 3.9.x

gravitee-gateway-handlers/gravitee-gateway-handlers-api/pom.xml, gravitee-gateway-repository/pom.xml, gravitee-gateway-security/gravitee-gateway-security-apikey/pom.xml, gravitee-gateway-security/gravitee-gateway-security-jwt/pom.xml, gravitee-gateway-security/gravitee-gateway-security-oauth2/pom.xml, gravitee-gateway-services/gravitee-gateway-services-heartbeat/pom.xml, gravitee-gateway-services/gravitee-gateway-services-sync/pom.xml, gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml, pom.xml
=> Use repo dependencies from the new APIM monorepo - 3.8.x

gravitee-gateway-handlers/gravitee-gateway-handlers-api/pom.xml, gravitee-gateway-repository/pom.xml, gravitee-gateway-security/gravitee-gateway-security-apikey/pom.xml, gravitee-gateway-security/gravitee-gateway-security-jwt/pom.xml, gravitee-gateway-security/gravitee-gateway-security-oauth2/pom.xml, gravitee-gateway-services/gravitee-gateway-services-apikeyscache/pom.xml, gravitee-gateway-services/gravitee-gateway-services-heartbeat/pom.xml, gravitee-gateway-services/gravitee-gateway-services-subscriptions-cache/pom.xml, gravitee-gateway-services/gravitee-gateway-services-sync/pom.xml, gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml, pom.xml
=> Use repo dependencies from the new APIM monorepo - 3.0.x

gravitee-gateway-handlers/gravitee-gateway-handlers-api/pom.xml, gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/manager/ApiManagerTest.java, gravitee-gateway-repository/pom.xml, gravitee-gateway-security/gravitee-gateway-security-apikey/pom.xml, gravitee-gateway-security/gravitee-gateway-security-jwt/pom.xml, gravitee-gateway-security/gravitee-gateway-security-oauth2/pom.xml, gravitee-gateway-services/gravitee-gateway-services-heartbeat/pom.xml, gravitee-gateway-services/gravitee-gateway-services-sync/pom.xml, gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml, pom.xml
=> Use repo dependencies from the new APIM monorepo - 3.5.x

pom.xml
=> chore: update gravitee-api-management dependency

pom.xml
=> chore: update gravitee-api-management dependency - 3.0.x

pom.xml
=> chore: update gravitee-api-management dependency - 3.5.x

pom.xml
=> chore: update gravitee-api-management dependency - 3.8.x

pom.xml
=> chore: update gravitee-api-management dependency - 3.9.x

pom.xml
=> chore(alert): bump alert-api to 1.7.1

.snyk
Snyk SAST analysis run against test code leads to unrelevant errors.
This .snyk policy file make snyk ignore code under /src/test/ directories.
=> ci: init snyk policy file to exclude test code from snyk analysis

docker/Dockerfile
Closes gravitee-io/issues#6139
=> chore: Upgrade OpenJDK Base Image

pom.xml
https://github.com/gravitee-io/issues/issues/6435
=> fix: bump gravitee-license-node.version to 1.3.0-SNAPSHOT fixes policies license issues

gravitee-gateway-services/gravitee-gateway-services-endpoint-discovery/src/main/java/io/gravitee/gateway/services/endpoint/discovery/EndpointDiscoveryService.java, gravitee-gateway-services/gravitee-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/EndpointHealthcheckService.java, pom.xml
https://github.com/gravitee-io/issues/issues/6306
fix: fix healthcheck stopping after gateway restarts
Ensure EndpointDiscoveryService and EndpointHealthcheck services are started before the SyncService,
As they consume events produced by SyncService.
We choose to override the getOrder() for EndpointDiscoveryService and EndpointHealthcheck, instead of increasing the SyncService one,
Cause we will get rid of those both services plugin in future versions.
=> fix: fix healthcheck stopping after gateway restarts

pom.xml
https://github.com/gravitee-io/issues/issues/6122
=> fix: bump gravitee-license-node.version to 1.3.0-SNAPSHOT fixes policies licenses issues

docker/Dockerfile, docker/Dockerfile-dev
We are moving to the `eclipse-temurin:11-jre-focal` base image for better security.
=> Change FROM image in Dockerfiles

gravitee-gateway-services/gravitee-gateway-services-debug/src/main/java/io/gravitee/gateway/debug/vertx/VertxDebugConfiguration.java
Issue: https://github.com/gravitee-io/issues/issues/6568
First this PR needs to be merged: https://github.com/gravitee-io/gravitee-node/pull/93
=> Add possibility to pre-define Vertx HTTP Server host name and port

.circleci/config.yml
The goal of this PR is to be able to use always the same tag when we create a docker image for APIM from master or any support branches.
This tag would be called `BranchName`-latest.
On top of that, we would push these tags on dockerhub.
=> Improve dev docker images generation

pom.xml
Related to https://github.com/gravitee-io/issues/issues/6574
Bump was missing in https://github.com/gravitee-io/gravitee-gateway/pull/818
=> fix: bump gravitee-gateway-api version

.circleci/config.yml, gravitee-apim-console-webui/sonar-project.properties, gravitee-apim-gateway/sonar-project.properties, gravitee-apim-portal-webui/sonar-project.properties, gravitee-apim-repository/sonar-project.properties, gravitee-apim-rest-api/sonar-project.properties, pom.xml
Replace https://github.com/gravitee-io/old-gravitee-api-management/pull/334
**Issue**
NA
- Disable SonarCloud comment on GitHub PR to avoid notif flood
- Use CircleCI's matrix job to trigger analysis for all APIM sub projects
TODO: 
- Make coverage work for Java projects 
🚀 &nbsp;&nbsp;CI was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/add-sonar/index.html)
_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.
=> ci: improve SonarCloud setup and add analysis of Rest API
